---
# -1 maximum browsers the machine can open
max_workers: -1

# google search
serp_api_key:

# blacklisted words when sanitizing HTML 
blacklist_text:
  - read more
  - more info
  - more articles
  - weiterlesen
  - mehr infos

# blacklisted URLs when searching for google results
blacklist_urls: 
  - amazon
  - youtube
  - pinterest
  - book

# whitelisted HTML tags
whitelist_tags:
  - b
  - p
  - h1
  - h2
  - h3
  - h4
  - h5
  - h6
  - img
  - ul
  - ol
  - li
  - table
  - thead
  - tbody
  - tr
  - th
  - td
